% Synthetic CNF problem (unsat) — generated by script
cnf(c0, axiom, (~p3(X2) | p2(X1,const_c) | p1(const_a,const_c))).
cnf(c1, axiom, (~p5(X3) | ~p4(X2,X2))).
cnf(c2, axiom, (~p3(const_a,X3))).
cnf(c3, axiom, (~p1(X3) | ~p1(const_c,X2))).
cnf(c4, axiom, (~p2(X2) | ~p3(const_a,X1))).
cnf(c5, axiom, (~p3(X1,X3))).
cnf(c6, axiom, (~p2(X1) | p2(const_b))).
cnf(c7, axiom, (p5(X3) | p3(const_a))).
cnf(c8, axiom, (p2(X2) | ~p2(const_a))).
cnf(c9, axiom, (p2(X1,const_c) | p1(X3,X1) | ~p2(X3,const_c))).
cnf(c10, axiom, (~p3(const_a,X3))).
cnf(c11, axiom, (p3(const_a,X3))).
