% Synthetic CNF problem (unsat) — generated by script
cnf(c0, axiom, (p2(X,a) | p2(c,Y) | ~p1(W,Y))).
cnf(c1, axiom, (~p1(c,Y) | p4(d))).
cnf(c2, axiom, (p5(c,U) | p5(b))).
cnf(c3, axiom, (p5(b,d))).
cnf(c4, axiom, (~p2(a,a))).
cnf(c5, axiom, (p3(Z))).
cnf(c6, axiom, (~p1(V,W))).
cnf(c7, axiom, (~p5(a) | ~p2(d))).
cnf(c8, axiom, (~p5(Z))).
cnf(c9, axiom, (p4(b) | ~p3(Y,V) | p5(Y,V))).
cnf(c10, axiom, (~p1(W,Y))).
cnf(c11, axiom, (p1(W,Y))).
